import type { Product, Category } from "./types"

export const categories: Category[] = [
  {
    id: "1",
    name: "Boys Collection",
    slug: "boys",
    color: "blue",
    description: "Cool and comfortable clothes for boys",
  },
  {
    id: "2",
    name: "Girls Collection",
    slug: "girls",
    color: "pink",
    description: "Beautiful and stylish clothes for girls",
  },
]

export const mockProducts: Product[] = [
  // Boys Products
  {
    id: "1",
    name: "Space Explorer T-Shirt",
    description: "Comfortable cotton t-shirt with space theme design",
    price: 25.99,
    originalPrice: 32.99,
    images: ["/boys-space-explorer-t-shirt.png"],
    category: "boys",
    season: "summer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Navy Blue", "Dark Gray", "Black"],
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    name: "Adventure Cargo Shorts",
    description: "Durable cargo shorts perfect for outdoor adventures",
    price: 34.99,
    images: ["/boys-cargo-shorts-khaki.png"],
    category: "boys",
    season: "summer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Khaki", "Navy", "Olive Green"],
    inStock: true,
  },
  {
    id: "3",
    name: "Superhero Hoodie",
    description: "Cozy hoodie with superhero graphics",
    price: 42.99,
    originalPrice: 49.99,
    images: ["/boys-superhero-hoodie-blue.png"],
    category: "boys",
    season: "winter",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Royal Blue", "Red", "Black"],
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    name: "Denim Jacket",
    description: "Classic denim jacket for stylish layering",
    price: 55.99,
    images: ["/boys-denim-jacket-classic-blue.png"],
    category: "boys",
    season: "winter",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Classic Blue", "Dark Wash"],
    inStock: true,
  },
  // Girls Products
  {
    id: "5",
    name: "Rainbow Unicorn Dress",
    description: "Magical dress with unicorn print and rainbow colors",
    price: 38.99,
    originalPrice: 45.99,
    images: ["/girls-unicorn-dress-rainbow-colors.png"],
    category: "girls",
    season: "summer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Rainbow", "Pink", "Purple"],
    inStock: true,
    featured: true,
  },
  {
    id: "6",
    name: "Butterfly Flutter Skirt",
    description: "Twirly skirt with beautiful butterfly patterns",
    price: 28.99,
    images: ["/girls-butterfly-skirt-pink-purple.png"],
    category: "girls",
    season: "summer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Pink", "Purple", "Lavender"],
    inStock: true,
  },
  {
    id: "7",
    name: "Princess Castle Top",
    description: "Sparkly top with princess castle design",
    price: 32.99,
    images: ["/girls-princess-castle-top-sparkly-pink.png"],
    category: "girls",
    season: "summer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Pink", "White", "Gold"],
    inStock: true,
    featured: true,
  },
  {
    id: "8",
    name: "Flower Power Leggings",
    description: "Comfortable leggings with floral print",
    price: 24.99,
    originalPrice: 29.99,
    images: ["/girls-floral-leggings-colorful-flowers.png"],
    category: "girls",
    season: "winter",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Floral Pink", "Floral Purple", "Floral Blue"],
    inStock: true,
  },
]
